### ISSUE TITLE
1. Mock up basic design

### ISSUE THREAD

**Issue by thgaskell** [devleague/omnimood#15]
- [x] wireframes/whiteboard what you think it could look like
- [x] describe your user(s)
- [x] describe features/functions of app (there will be many, prioritize MVP features to nice-to-have features

**Update:** https://github.com/devleague/omnimood/issues/15#issuecomment-250950509

> MVP
> - Display a "mood-map" of the world with countries color-coded according to emojis parsed from Twitter tweets.
> 
> Key Features
> - Real-time color change
> - Filter by emoji
> - Filter by country (by clicking on country)
> - Visually pleasing (intuitive and clean)
> 
> Nice-to-Have Features:
> - Display additional data like trending hashtags, historical graph, etc.
> - 3D View

**Comment by adam-akamine** [comment]
World Map (Default view)
![worldmapdefault](https://cloud.githubusercontent.com/assets/931205/19018142/1154dbd4-87f2-11e6-8055-1b12249ba291.png)

**Comment by adam-akamine** [comment]
Country View
![countryview](https://cloud.githubusercontent.com/assets/931205/19018144/20ed035a-87f2-11e6-93cc-27eb4bf6877b.png)

**Comment by adam-akamine** [comment]
Describe your users:
- Open to Public web users
- Catered to desktop (non-smartphone) viewers

**Comment by adam-akamine** [comment]
MVP
- Display a "mood-map" of the world with countries color-coded according to emojis parsed from Twitter tweets.

Key Features
- Real-time color change
- Filter by emoji
- Filter by country (by clicking on country)
- Visually pleasing (intuitive and clean)

Nice-to-Have Features:
- Display additional data like trending hashtags, historical graph, etc.
- 3D View

**Comment by adam-akamine** [comment]
Sent to Kelli

**Comment by adam-akamine** [comment]
notes from meeting
- Pick 3 - 10 solid colors, make them muted.
- Use lighten and darken SASS functions
- pick 1 font, sans-serif, look for a good one for data/map, black/white font colors
- make selected country/changing country light up for focus
- historical feature more important than trending hashtags and 3D view

stretch goal
- track "special events" by amount of emoji in a period of time
