### ISSUE TITLE
Create fake tweet generator

### ISSUE THREAD

**Issue by thgaskell** [devleague/omnimood#21]
# Description

It looks like Twitter is rate limiting the requests when everyone's running the project from the same IP address. In order to resolve that, it looks like it would be a good idea to have a small process that mimics the data being sent from twitter.
# Action

Create a small node process that generates fake tweets.
# Tasks
- [ ] Create a callback in `setTimeout` to mimic sending tweets to the server. Twitter seems to send a tweet roughly every `100 ms`.
- [ ] Create method to send a `POST` request to `/api/tweets` with the following JSON payload that has at least`text`, `coordinates`, and `timestamp` values.
# Resources

**Example JSON payload**

``` json
{
  "text": "#AMP FTW! 😀⚡️",
  "coordinates": {
    "coordinates": [
        -75.14310264,
        40.05701649
    ],
    "type":"Point"
  },
  "created_at": "Wed Aug 27 13:08:45 +0000 2008"
}
```

Full documentation here: https://dev.twitter.com/overview/api/tweets

**Comment by adam-akamine** [comment]
Fake tweet generator created to fill in the "gaps" when we are rate limited.
But we also each have our own API keys, so the fake tweet generator will be our backup in case the Twitter servers crash or we get individually rate limited.
