### ISSUE TITLE
Determine how to calculate colors on main map (heat map)

### ISSUE THREAD

**Issue by adam-akamine** [devleague/omnimood#24]
Most of this is just me logging my thoughts so I can justify whatever solution I find...
Need a formula for calculating mood level.

Possible calculation 1:
All countries start at "green" mood level, because there are 26 positive emojis and 18 negative emojis.
Each positive emoji is worth +1, each negative emoji is worth -1.
So each country starts at 26 + -18 = positive 8.
Every incoming emoji will either add +1, 0, or -1 to total mood count for each country.
**Problem: scale of gradient needs to change constantly...for example a -10000000 value would be how much darker than -10? At what point does it become a shade lighter? Scale differently for every country? NOPE**

**Comment by adam-akamine** [comment]
Possible calculation 2:
Calculate the percentages of positive emojis vs. neutral emojis vs. negative emojis and set the color according to that percentage. Ex: > 70% positive = greenish, < 50% = reddish, everything else yellow or white depending on gradient scale.
Requires keeping track of more than just a single value to represent mood.
**Problem: Edge cases of extreme amounts of positive or negative emojis could cause this to break...need some kind of "neutralization" over time...**

**Comment by thgaskell** [comment]
I think it depends on what you're trying to illustrate.

`Calculation 1` sounds like it's useful for comparing countries with each other. 
- Country A is 10 times happier than country B.
- Country C is relatively neutral compared to everyone else.

`Calculation 2` seems like you are just looking at the average mood of a country.
- Most of the tweets in Country A are happy.

It's possible you will not data for some countries, how will these be displayed?

**Comment by adam-akamine** [comment]
Hmm good observation, maybe calculation 1 would be good for implementing other metrics in single country views. I think calculation 2 will be good enough for the heat map for now.

I guess the countries without tweets can remain a neutral color. I'll ask Kelli for suggestions.

Thanks!
