### ISSUE TITLE
Time, dead time, resetting time...

### ISSUE THREAD

**Issue by adam-akamine** [devleague/omnimood#25]
Might be good to track time since last tweet for each country.
This way we can add a "neutralizing" effect so that when a country "goes to sleep" they don't remain red or green but drift towards the neutral color.
OR
Implement a reset time for each country
- reset each country back to neutral at the country's determined "bed time"

Or a little bit of both...thoughts?

**Comment by thgaskell** [comment]
Funny, I was just thinking about this one!

It might be cool if the country "flashed" whenever a new tweet is made from that place.

Or since you get the lat/lng values from each tweet, you could make a little blip animation to show where that tweet came from on the map? Maybe the emoji could be used to mark what emoji got counted?

**Comment by adam-akamine** [comment]
Yeah it would be great if we could get an emoji to float up at the coordinates where the tweet came from!
That raises another issue tho - can we map that point onto our D3 map? Wouldn't we have to reference Google Maps or another API and make it scale down to our map?

**Comment by theRemix** [comment]
no you don't have to reference google maps or other api.

if you have a map using d3.geo, then you can use points on your d3 map by lat/lng.

**Comment by theRemix** [comment]
i don't think you have to worry too much about indicating that parts of the world are asleep.

i was thinking that you could maintain the mood based on the previous average of when a country was awake, though i think that there is still plenty of tweets and emoji's being emitted at all hours.
